FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir hatch

COPY pyproject.toml .
RUN pip install --no-cache-dir -e .

COPY . .

CMD ["uvicorn", "flatchef.main:app", "--host", "0.0.0.0", "--port", "8000"]
